export const HISTORY_READ_START = 'HISTORY_READ_START';
export const HISTORY_READ_SUCCESS = 'HISTORY_READ_SUCCESS';
export const HISTORY_READ_FAILED = 'HISTORY_READ_FAILED';

export const HISTORY_GRID_STATE_CHANGED = 'HISTORY_GRID_STATE_CHANGED';
