export const LOGIN_CHANGED = 'LOGIN_CHANGED';

export const LOGIN_SIGN_IN_START = 'SETTINGS_READ_SUCCESS';
export const LOGIN_SIGN_IN_SUCCESS = 'LOGIN_SIGN_IN_SUCCESS';
export const LOGIN_SIGN_IN_FAILED = 'LOGIN_SIGN_IN_FAILED';
