export const SETTINGS_READ_START = 'SETTINGS_READ_START';
export const SETTINGS_READ_SUCCESS = 'SETTINGS_READ_SUCCESS';
export const SETTINGS_READ_FAILED = 'SETTINGS_READ_FAILED';

export const SETTINGS_UPDATE_START = 'SETTINGS_UPDATE_START';
export const SETTINGS_UPDATE_SUCCESS = 'SETTINGS_UPDATE_SUCCESS';
export const SETTINGS_UPDATE_FAILED = 'SETTINGS_UPDATE_FAILED';

export const SETTINGS_JSON_VALUE_CHANGED = 'SETTINGS_JSON_VALUE_CHANGED';
